version: "3"
services:
  teste_api:
    container_name: teste_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - test-net

  teste_db:
    container_name: teste_db
    image: postgres:9.6.22-alpine
    env_file:
      - .env
    networks:
      - test-net

networks:
  test-net:
    driver: bridge
