version: "3"
services:
  teste_api:
    container_name: teste_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/api
      - ./node_modules/:/home/api/node_modules/
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - teste_db
    networks:
      - test-net

  teste_db:
    container_name: teste_db
    image: postgres:9.6.22-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - test-net

networks:
  test-net:
    driver: bridge
